### ISSUE TITLE
Database tables inside the Postgres

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#1]
Create the tables inside the `maketapp` DB. We will begin with the basic tables `customers` and `employees`. We are gonna need the basic columns for each table:

* `customer_id` and `employee_id`
* `first_name`
* `last_name`
* `email_adress` and `phone` for the customers
*  `email_adress` and `phone` for the employee
* `registration_date` for the customers

Feel free to add any additional columns that you may consider would be necessary.

**Comment by rayapetkova** [comment]
I made the two tables. The column "phone" in both tables is casted to data type "TEXT" because that way the leading zero is not disappearing.

[customers_and_employees.txt](https://github.com/Stake-And-Rope/market-app/files/11382406/customers_and_employees.txt)

**Comment by karastoyanov** [comment]
Perfect! At this point we can start making the integration between the app and the DB. For this, we will start to prepare some py scripts which will communicate with the Postgres server and will execute specific [CRUD ](https://www.crowdstrike.com/cybersecurity-101/observability/crud/#:~:text=CRUD%20is%20the%20acronym%20for,in%20relational%20and%20NoSQL%20databases.)operations.

I am closing this Issue and will reschedule a new story with instructions how to proceed with the next steps. 
Well done! 👍
