### ISSUE TITLE
New user registration though the graphical user interface

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#11]
For the next story I will need help with integrating the database into the application. :slightly_smiling_face:

We have to implement new users registration in the [register](https://github.com/Stake-And-Rope/market-app/blob/development/pyqt5-gui/register.py) file. After the user introduces it's data and clicks on the "Register" button, we need to execute a query which will create a new record inside the `customers` table. We will begin step by step:

* I have prepared a new function `create_new_account` inside the `register` file, pressing the Register button will calls that func.
* For the user ID, we want to have a little bit more complex ID's stored in the table. First try to write an algoritm which generates a random 10-digits number and then checks if a customer with this ID is already existing in the table, if this return True --> generate new ID.

**Comment by rayapetkova** [comment]
Last change: 2abeb5d

**Comment by karastoyanov** [comment]
* Last change: 8f32f2fcb092606a7d9af2dd611b20629715363f

**Comment by karastoyanov** [comment]
Last change: a069473c3bef43851cad5826de95d391d16def84
* Error Box in registration form implemented
* Check for unique `username` in DB functionality added
* Minor update

**Comment by karastoyanov** [comment]
Last change 0daa81105fd6815d176af05d39c8427e8b6cda72

 * User registration in the DB improved, new users receive additional `_marketapp` string in the username
 * Role with custom permissions implemented and automatically granted to all new users
 * Minor GUI fixes
