### ISSUE TITLE
Login Window

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#12]
We need to create the Login window and implement the back-end behind it. Start with a simple pyqt window for the login screen. For now we will stick to very basic UI. 

You will need four layouts in total:
* One Vertical Layout will receive the labels and the textboxes
* One Horizontal Layout will receive the buttons Login/Register
* One Vertical Layout will receive the previous two layouts
* One more Vertical Layout, the main one, which will be as parent to all other layouts

**Comment by rayapetkova** [comment]
Last change: 0e77fd7

**Comment by karastoyanov** [comment]
Last change 5f36432f7143f00b3df9f23eff96ffa923960dac
