### ISSUE TITLE
Main Categories database table

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#16]
`categories` table should consists of the following columns:

* `category_id` - :warning: I propose to make this field text value and autogenera the IDs with prefix CAT-XXXXXX
* `category_name`
* `total_subcategories` will count how much subcategories are under the specific category
* `total_items` - will count the number of the subcategories inside the specific category
* `last_modified`  - timestamp

Any other columns could be added as well

**Comment by rayapetkova** [comment]
Made the categories table:
[categories_table.txt](https://github.com/Stake-And-Rope/market-app/files/11436067/categories_table.txt)
