### ISSUE TITLE
Subcategories database table

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#17]
This one is related to #16 

`subcategories` will have similar columns as `categories`

* `subcategory_id` - again, I propose to leave this field as text value and autogenerate the IDs with prefix SUBCAT-XXXXXX
* `subcategory_name`
* `total_items` - the total number of items inside that subcategory
* `last_modified` - timestamp

Any other columns could be added as well

**Comment by rayapetkova** [comment]
Made the subcategories table:
[subcategories_table.txt](https://github.com/Stake-And-Rope/market-app/files/11436124/subcategories_table.txt)
