### ISSUE TITLE
Main WIndow Basic Structure

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#19]
We will use [main_menu](https://github.com/Stake-And-Rope/market-app/tree/main_menu) branch to make the main menu window.

**Comment by karastoyanov** [comment]
TBD brainstorm with main subjects:

* GUI style
* Objects and Layout Structure

**Comment by karastoyanov** [comment]
Basic UI created with 8b5c3e0d59a1a4484319c7b5392f0c8e50c67a18 and a688b8b14a1fb09b30206eb3dbaa2c31443311d3

We managed to create new objects inside the UI using for loop, which will save us a lots of repeating code in the future.

So far we will switch the main_layout to QGridLayout() class instead of QHBoxLayout().

**Comment by karastoyanov** [comment]
Main Menu slighty reworked:
* We are going to implement the `QGroupBox` class which will create separate groups for the layouts and will make them more visible during the dev process

2e128e8efe63fc399afe6af058aeca509980d798

**Comment by rayapetkova** [comment]
Last changes: 9551bab

- Made a QGroupBox for the left buttons layout
- Added the layout in the left_buttons_groupbox

**Comment by rayapetkova** [comment]
Last changes: 8b7ac4fd68067f58f7a324b0a62081972c632a7c

- Added the basic structure of creating the categories layout.
- QGridLayout in QGroupBox

**Comment by karastoyanov** [comment]
Last changes: 
031f9aa0eb7983b15d67052d79046a7000b01eaa
db87ebfe322b2f6f69ee2b96b95c0c87e345bdc6

* Basic GridLayout for the categories create

we will follow this logic to display the separate objects:


```python
        postgres_conn.POSTGRES_CURSOR.execute(f"SELECT category_name, category_description, category_function FROM categories ORDER BY category_name ASC;")
        result = postgres_conn.POSTGRES_CURSOR.fetchall()
        categories = deque([x[0] for x in result[0:3]])
        categories_description = deque([x[1] for x in result[0:3]])
        categories_functions = deque([x[2] for x in result[0:3]])

        print(categories_functions)

        for row in range(3):
            for col in range(4):
                if categories:
                    current_groupbox = QGroupBox()
                    current_vertical_layout = QVBoxLayout()
                    category_name = QLabel(categories.popleft())
                    category_name.setFont(QFont(fonts[0], 9))
                    category_description = QLabel(categories_description.popleft())
                    category_description.setFont(QFont(fonts[0], 9))
                    category_button = QPushButton()
                    current_function_name = categories_functions.popleft()
                    current_function = getattr(food_open(), current_function_name)
                    category_button.clicked.connect(lambda: current_function())
                    current_vertical_layout.addWidget(category_name)
                    current_vertical_layout.addWidget(category_description)
                    current_vertical_layout.addWidget(category_button)
                    current_groupbox.setLayout(current_vertical_layout)
                    categories_grid_layout.addWidget(current_groupbox, row, col)
```

🔖 Still we need to figure out how to handle the buttons and their functions

**Comment by karastoyanov** [comment]
Last update: ab6f88838551b79f6adc4babcb23bfbab90e3fa9

@rayapetkova I somehow managed to call function by a string, taken from the database


![Image](https://github.com/Stake-And-Rope/market-app/assets/86146020/e78a89e8-0d96-4cec-8df6-4f851a719484)

but for some reason the button executes the same function. Take a look on the last commit and especially these sections. We will continue improving the code and find the proper solution, it seems that we are very close to the proper solution.



![Image](https://github.com/Stake-And-Rope/market-app/assets/86146020/f8700585-ef3c-45e2-a855-9a358b3ba1da)



![Image](https://github.com/Stake-And-Rope/market-app/assets/86146020/c4e2e98e-023f-48b0-8042-fd308a6178ef)

**Comment by rayapetkova** [comment]
It looks really good with the dictionary and this will be the best way to call the functions. I will take a look in more details tomorrow.

**Comment by karastoyanov** [comment]
Last changes with: 1f37b45ea7882e7f267751fa06c1285d911d1478, 781833a3696f6fdaf4fcb7bc5b41409bd97483d3

Calling the right button is fixed using the following logic

```python
        def food_open():
            print("I am eating some food")
            
        def books_open():
            print("I am reading books")
        
        def drinks_open():
            print("I am drinking some drinks")
            
        functions_dict = {
            'food_open': lambda: food_open(),
            'books_open': lambda: books_open(),
            'drinks_open': lambda: drinks_open(),
        }
```

```python
        category_button.clicked.connect(functions_dict[current_function_name])
```

Good job, @rayapetkova! 💯 

Next steps regarding the structure are described in #28

**Comment by karastoyanov** [comment]
Last Updates:

9a58a255d2b77862bf8bfc7b19087ef699dc4ff7


* user info layout updated


![Image](https://github.com/Stake-And-Rope/market-app/assets/86146020/4741333c-471c-4c9c-8ff0-0e961db49cee)

**Comment by karastoyanov** [comment]
Last update: [9e05aa7](https://github.com/Stake-And-Rope/market-app/commit/9e05aa740d2cbf077b72bbacdd268bfd0da5569b)
