### ISSUE TITLE
Test the backend script for the portfolio management

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#24]
Test the functionality of the [portfolio script](https://github.com/Stake-And-Rope/market-app/blob/development/db_handle/manage_portfolio.py) and describe the result.

* try to creatye new categories, sub-categories and products inside the database
* point any potential bugs/issues.

**Comment by rayapetkova** [comment]
Last change: 299d07339327d6715e6c94dc1d8a8f86819851a0

- Commented parts of the code 
- Made small changes in the queries - wrote 0's in the creating of the new category and new subcategory
- Change if statements so they doesn't throw an error - deleted the function len() in front of the lists 
- Commented the last three functions
