### ISSUE TITLE
Add a new column to products table

### ISSUE THREAD

**Issue by rayapetkova** [Stake-And-Rope/market-app#25]
This is related to #20  

- Add a new column `unit_of_measure` to products table - data type TEXT

**Comment by karastoyanov** [comment]
Should be fine
![image](https://github.com/Stake-And-Rope/market-app/assets/86146020/890270c7-3fae-41b1-a600-091b6edc78f8)


Try to implemented the new column in the script from #21 `create_new_items()` function and run new tests related to #24 

:bulb: I recommend to delete all the current demo data and run again tests with new data.

**Comment by rayapetkova** [comment]
Last changes: [1cbd2ce](https://github.com/Stake-And-Rope/market-app/commit/1cbd2cefa4f88578878e424a9d9938f5e5333fe6)

- Implemented the new column "unit_of_measure" in the script
- Deleted all demo data (except the last one I made recently)
- Runned again with a new test data
