### ISSUE TITLE
New column in `products` table

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#27]
Add new column in `products` table named `image_url` which will contain an url address to the image for the specific product. 

We can use a simple text data type to store the url address, inside the application we will indicate that string to the proper pyqt method which will initialize the image in the user interface.

**Comment by rayapetkova** [comment]
Added a new column image_url with data type TEXT.

[new column image_url.txt](https://github.com/Stake-And-Rope/market-app/files/11473056/new.column.image_url.txt)
