### ISSUE TITLE
Demo data in the PostgreSQL

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#28]
Fill in the database with some useful data that we can use to build next part of the GUI

**Comment by rayapetkova** [comment]
Last changes: 27d5e5d
- Added new categories, subcategories and products

![Image](https://github.com/Stake-And-Rope/market-app/assets/122923696/a3898e76-1715-4196-8d40-bf6e517ddcec)



![Image](https://github.com/Stake-And-Rope/market-app/assets/122923696/3f01e6ab-ae89-4345-ae37-64a7160dda11)



![Image](https://github.com/Stake-And-Rope/market-app/assets/122923696/42ef4123-7cf6-47df-abaa-378e42292439)

**Comment by karastoyanov** [comment]
@rayapetkova we have two categories with `Food` name. Choose one of them and change it's name, at this point it's not important the exact name of demo data.

try to find some png images and insert their URL's in `products` table, `image_url` column. We will try to use this url to point it to the object in the GUI for the respective category. You can use [https://www.flaticon.com/](https://www.flaticon.com/) to download some random pictures

**Comment by karastoyanov** [comment]
Fill in new data in `categories` table and use that data to display some test categories in the UI

* New column with image url address has been added. Get some URLs from web and use them as objects for the categories in the UI
* Try to re-arrange the objects, experiment with few different variants, it's up to you. We will take final decision about the format

**Comment by rayapetkova** [comment]
- Deleted the old demo data and added 12 new categories with URLs

![image](https://github.com/Stake-And-Rope/market-app/assets/122923696/888263b9-ee73-43b7-841a-c3754886cfd7)

**Comment by karastoyanov** [comment]
* New column in `customers` added --> `total_orders`, which will store the total number of orders for each customer

![Image](https://github.com/Stake-And-Rope/market-app/assets/86146020/07691174-cb0f-4980-b8b9-409258330780)

**Comment by karastoyanov** [comment]
New function in [manage_portfolio](https://github.com/Stake-And-Rope/market-app/blob/development/db_handle/manage_portfolio.py) functionality is needed --> update the current number of categories/subcategories and products in the database
