### ISSUE TITLE
Products display in the Main menu

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#29]
After we are done(completly or partially) with #28, we will start building the main part of the main menu, the products section.

**Comment by karastoyanov** [comment]
Last changes with 518912ff23e13a30ee6495a4a8acfd68c65a237a

* Pixmap fixed, image is taken directly from the database and displayed in QLabel object
* QLabel object for the category image is moved above the button


⚠ Taking the URL data from the database and feeding it to the Framework is quite a slow process. We may think for another solution, maybe we have to store the images inside the project directory

**Comment by karastoyanov** [comment]
Last changes with 2c0fc287629a1ef1a5f76e8501b3034328383d7a

* Category Images Stored Locally to improve the code and the application loading time

**Comment by karastoyanov** [comment]
Last changes with 2c70691754ffed9e2f73281d6a8c79c4672d7917

* Categories names and descriptions Updated with new style
* `QGraphicsDropShadowEffect()` class implemented instead of `.setStyleSheet()` to remove the background color

* Current styles and shadow effects are just for testing purposes. Customizing needs to be done.

**Comment by rayapetkova** [comment]
Last changes: 2f080b5
- Used a random image and reduced its opacity
- Added the image in directory img --> categories
- Added it as a background in category "Accessories"
- First try (unsuccessful) : tried to reduce the opacity of the groupbox but it changed the opacity of all the objects in it 
- All current images in img --> categories are only for test purposes and need to be changed later 

![image](https://github.com/Stake-And-Rope/market-app/assets/122923696/b0bf9d4e-8029-44b5-b244-7a5e101613ce)

**Comment by rayapetkova** [comment]
Last changes: 16dcd5f
- Deleted commented lines that I think won't be needed
- Added a background for the category_name labels
- Made the background fading, rounded and set a color white (needs to be changed if we find a better one)
- aligned the category_name labels in center

**Comment by karastoyanov** [comment]
Last changes: 387827ccf42956b2f0ccbb664bce621405ad7cae 02090570bca52d0bdf0fe5d1e6116ee98ccb2014

* Slightly reworked the categories, yet we have to experiment with the colors for the categories description
* Left layout buttons modified
