### ISSUE TITLE
Sub-categories Menu

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#37]
We need to start developing the sub-categories menu.

The entire work will be done on a separate branch [subcats_menu](https://github.com/Stake-And-Rope/market-app/tree/subcats_menu). Create new file `subcategories.py` and work on it to display the different sub-categories for each category from the DB.

The goal is to have one single file which will initialize all the respective subcategories, depending on the user input (button click). 

You can begin will copying the main structure from `categories`.

**Comment by karastoyanov** [comment]
Last changes:
df5a25c257f21f01814772578f63e9fa6089941c
60178c31e07371b0f5763574eaabd6ff670bc45b
bce9c03a7fe0314b4a22206fa54b5aed4dca50c7

* basic relationship between main_menu <-> subcategories created
* minor GUI changes

**Comment by rayapetkova** [comment]
Last changes: ac3d5f8
- Added all subcategories images in img --> subcategories
- Made one common function in pyqt5-gui --> subcategories and deleted all the previous ones
- Applied the added images to the subcategories QGroupBoxes - pyqt5-gui --> subcategories

This is how the subcategories look like in the database:



![Image](https://github.com/Stake-And-Rope/market-app/assets/122923696/571a2a07-3a7d-40f9-b9c6-2826cec8a143)



![Image](https://github.com/Stake-And-Rope/market-app/assets/122923696/1fcc95ac-6e6c-449f-a672-15d8e6633749)
