### ISSUE TITLE
CRUD test script

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/market-app#8]
In addition to #1 we will need a CRUD script written in Python which will help us to test the main functionalities on the current DB structure.

⚠️ Main objectives:
* the script should be placed in `db_handle` directory
* inside the script there should be one main function --> `crud_operations`, inside the main function four additional child functions to be implemented: `create`, `read`, `update`, `delete`
  * `create` function should insert new record in any of the tables(your choice)
  * `read` function should read the entire table and output the records
  * `update` function should update any of the fields on a specific record based on a given attribute, e.g. based on customer/employee ID update the first name
  * `delete` function should delete a record based on a given attribute
* in order to initiate connection between the script `crud_operations` and the database servers, you will have to import the `postgres_conn` file
* Based on the user input, the main function should call any of the child functions

💡 A very basic py script is attached as a template, you can rely on it and keep improving the code.
[template.txt](https://github.com/Stake-And-Rope/market-app/files/11383284/template.txt)

**Comment by rayapetkova** [comment]
1. Last commit --> 2236874
2. I made all the CRUD operations (not sure if they all right)
3. I was thinking about doing an if condition in the update() and delete() functions. When I test the script and try to enter an invalid condition (for example customer_id = 20 and this ID doesn't exist) it gives error. I didn't manage to check if the condition is valid. Can you give me how to do it? 
4. Every time I use a function it shows this:
![image](https://user-images.githubusercontent.com/122923696/236171125-a053e1b2-7f3a-4075-8bd8-1baeca0d1e2d.png)
   What can I do for it to stop showing?
   
![image](https://user-images.githubusercontent.com/122923696/236171418-b9f652c7-4d02-4364-8635-94e182abd336.png)

**Comment by karastoyanov** [comment]
I have added some review on #9 . For now we will stick with this script, its idea was to make the first steps with managing the database though python script. With the further implementation withing the app, we will have to customize the queries 

Regarding the the error, you can try to implement try/except condition. You can put the entire SQL query execution under a `try` condition and raise an error in case the query doesn't execute properly.

A very basic example:
```python
try:
   postgress_conn.POSTGRES_CURSOR.execute('some SQL query')
   postgress_conn.POSTGRES_CONNECTION.commit()
except (Exception) as error:
   print("SQL error")
```

About the unwanted print, you can open `postgress_conn` file and comment these two lines:
![image](https://user-images.githubusercontent.com/86146020/236197618-5815c691-fdba-44a5-92b7-f8d8fe7f90cb.png)

**Comment by rayapetkova** [comment]
91914ba
